import Link from "next/link";

export default function CookiePolicy() {
  return (
    <main className="min-h-screen bg-cloud py-12 px-4">
      <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-md p-8 md:p-12">
        <h1 className="text-4xl md:text-5xl font-light text-midnight mb-4 tracking-tight">
          Cookie Policy
        </h1>
        <p className="text-charcoal/70 mb-8 font-light">
          Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>

        <div className="prose prose-lg max-w-none text-charcoal space-y-8">
          <section>
            <h2 className="text-2xl font-light text-midnight mb-4 mt-8">What Are Cookies</h2>
            <p className="leading-relaxed font-light">
              Cookies are small text files that are placed on your device when you visit a website. 
              They are widely used to make websites work more efficiently and provide information 
              to website owners.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-light text-midnight mb-4 mt-8">How We Use Cookies</h2>
            <p className="leading-relaxed font-light mb-4">
              The Midnight Travel Co. uses cookies to:
            </p>
            <ul className="list-disc pl-6 space-y-2 font-light">
              <li>Understand how visitors use our website</li>
              <li>Improve website functionality and user experience</li>
              <li>Analyze website traffic and user behavior</li>
              <li>Remember your preferences and settings</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-light text-midnight mb-4 mt-8">Google Analytics 4 (GA4)</h2>
            <p className="leading-relaxed font-light mb-4">
              We use Google Analytics 4 to collect and analyze information about how visitors use our 
              website. GA4 uses cookies and similar technologies to:
            </p>
            <ul className="list-disc pl-6 space-y-2 font-light">
              <li>Track page views and user interactions</li>
              <li>Understand visitor demographics and interests</li>
              <li>Analyze traffic sources and user behavior</li>
              <li>Measure website performance</li>
            </ul>
            <p className="leading-relaxed font-light mt-4">
              The information generated by these cookies about your use of our website is transmitted 
              to and stored by Google. Google may use this data to evaluate your use of the website, 
              compile reports on website activity, and provide other services relating to website 
              activity and internet usage.
            </p>
            <p className="leading-relaxed font-light mt-4">
              You can opt out of Google Analytics by installing the{" "}
              <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer" className="text-royal hover:underline">
                Google Analytics Opt-out Browser Add-on
              </a>
              . You can also manage your cookie preferences through your browser settings.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-light text-midnight mb-4 mt-8">Types of Cookies We Use</h2>
            
            <h3 className="text-xl font-light text-midnight mb-3 mt-6">Essential Cookies</h3>
            <p className="leading-relaxed font-light">
              These cookies are necessary for the website to function properly. They enable core 
              functionality such as security, network management, and accessibility.
            </p>

            <h3 className="text-xl font-light text-midnight mb-3 mt-6">Analytics Cookies</h3>
            <p className="leading-relaxed font-light">
              These cookies help us understand how visitors interact with our website by collecting 
              and reporting information anonymously. We use Google Analytics 4 for this purpose.
            </p>

            <h3 className="text-xl font-light text-midnight mb-3 mt-6">Functional Cookies</h3>
            <p className="leading-relaxed font-light">
              These cookies enable enhanced functionality and personalization, such as remembering 
              your preferences and settings.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-light text-midnight mb-4 mt-8">Managing Cookies</h2>
            <p className="leading-relaxed font-light mb-4">
              You have the right to accept or reject cookies. Most web browsers automatically accept 
              cookies, but you can usually modify your browser settings to decline cookies if you prefer. 
              However, this may prevent you from taking full advantage of our website.
            </p>
            <p className="leading-relaxed font-light">
              You can manage cookies through your browser settings. Instructions for popular browsers:
            </p>
            <ul className="list-disc pl-6 space-y-2 font-light mt-4">
              <li>
                <a href="https://support.google.com/chrome/answer/95647" target="_blank" rel="noopener noreferrer" className="text-royal hover:underline">
                  Google Chrome
                </a>
              </li>
              <li>
                <a href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences" target="_blank" rel="noopener noreferrer" className="text-royal hover:underline">
                  Mozilla Firefox
                </a>
              </li>
              <li>
                <a href="https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac" target="_blank" rel="noopener noreferrer" className="text-royal hover:underline">
                  Safari
                </a>
              </li>
              <li>
                <a href="https://support.microsoft.com/en-us/microsoft-edge/delete-cookies-in-microsoft-edge-63947406-40ac-c3b8-57b9-2a946a29ae09" target="_blank" rel="noopener noreferrer" className="text-royal hover:underline">
                  Microsoft Edge
                </a>
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-light text-midnight mb-4 mt-8">Third-Party Cookies</h2>
            <p className="leading-relaxed font-light">
              In addition to our own cookies, we may also use various third-party cookies to report 
              usage statistics and deliver content. These third parties may set their own cookies 
              or similar technologies on your device.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-light text-midnight mb-4 mt-8">Changes to This Policy</h2>
            <p className="leading-relaxed font-light">
              We may update this Cookie Policy from time to time to reflect changes in our practices 
              or for other operational, legal, or regulatory reasons. We will notify you of any 
              material changes by posting the updated policy on this page.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-light text-midnight mb-4 mt-8">Contact Us</h2>
            <p className="leading-relaxed font-light">
              If you have questions about our use of cookies, please contact us at:
            </p>
            <p className="leading-relaxed font-light mt-4">
              <strong>The Midnight Travel Co.</strong><br />
              Email: travel.midnightco@gmail.com
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-silver">
          <Link
            href="/"
            className="text-royal hover:text-midnight transition-colors font-light"
          >
            ← Back to Home
          </Link>
        </div>
      </div>
    </main>
  );
}
